### ISSUE TITLE
How to translate it into Chinese

### ISSUE THREAD

**Issue by marcosteam** [Alliance-Network/Amoeba#6]
I heard about this software on v2ex,a site built for Chinese devlopers.
But I think It would be hard to use without Chinese.
So do you have any plans to translate it into other language?Maybe I could help you to give some text!

**Comment by deeporist** [comment]
@marcosteam 
hello,v2er! the author has planned to support multilingualization(include chinese i think). 
there is a chat room:Tag:AAAABumXsuiwiAEgxf_HEIBjZm6Dagpla0p56iLHkZCDGNwnaTHyBzupg7ziP2Tv

from now there are some points confuse me. if amoeba is useing DHT to trans data, the reason of tor.exe running with it is not clear to me. maybe given a optional choose to enable tor make the whole thing more sensible with my idea(otherwise the tor does some work needed by amoeba's normal running). I also think we need more documents about the detail of amoeba's files and config.

**Comment by AllianceNetPR** [comment]
Thank you for your comments.

@deeporist 
In my understanding,
Tor.exe is not mandatory to share data. 
Amoeba was designed to overlay any networks including TCP, i2p, tor, etc. 
Tor is one of the options.

@marcosteam 
As I posted in chat room of Amoeba, 
we developer want to overcome the border of the language.
The document is enhanced in the near future.
We also announce a method in chat room in Amoeba to collect your helps in the near future.
